### ISSUE TITLE
Load options for feeds

### ISSUE THREAD

**Issue by mynkow** [Elders/ActivityStreams#10]
@SayliS @djimmytrovy 
Right now when loading a feed you can constrain the results using PagingOptions and SortOrder. These two are represented as a two parameters in the master method + overloads. My idea is to remove all the overloads and keep only one method with the following signature: 

```
    public interface IActivityStore
    {
        IEnumerable<Activity> Get(Feed feed, FeedOptions options);

        void Save(Activity activity);
    }

    public class FeedOptions
    {
        Paging Paging {get;set;}
        SortOrder Order {get;set}
    }
```

**Comment by ghost** [comment]
It is done. I will make a pull request to apply the changes when I test it

**Comment by mynkow** [comment]
https://github.com/Elders/ActivityStreams/commit/de301da58541d3a82470d8088adf3e84788986c7
